[tool.poetry]
name = "arbot"
version = "0.1.0"
description = ""
authors = ["IrakliMa <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
ccxt = "^1.59.76"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
